// ═══════════════════════════════════════════════════════════════════════════
// Twin Oaks OS — SAMPLE DATA (FR-003, "safe testing mode")
//
// Practice records so the whole app — receipts, invoices, sheep, print jobs,
// filament, banking, bills — can be exercised end to end, and then removed
// again without ever endangering the real books.
//
// ───────────────────────── THE SAFETY CONTRACT ─────────────────────────────
//
//   NOTHING IN THIS FILE CAN EVER DELETE A ROW THE OPERATOR ENTERED HIMSELF.
//
// That is not a promise made in prose — it is made in the structure:
//
//   1. MARKING. Every row this file creates is given an explicit id that
//      begins with `sample-` (see SAMPLE_ID_PREFIX). Ids are generated by the
//      app, never typed by the operator, never editable from any screen, and
//      never rewritten by an edit. So the mark cannot be scrubbed off a
//      sample row, and cannot be accidentally applied to a real one.
//
//   2. ONE DELETE. `deleteSampleRows` below is the ONLY function in this file
//      that calls `deleteMany`. It builds its own `where` clause — a caller
//      cannot supply one — and that clause always carries BOTH the account
//      scope AND an id filter restricted to ids that passed `isSampleId`.
//      An empty id list matches nothing rather than everything.
//
//   3. NO COLLATERAL DAMAGE. Some sample rows are parents of rows that would
//      cascade-delete with them (an invoice's payments, a spool's filament
//      uses, a ewe's events) or that would be silently detached from them
//      (an expense pinned to a piece of equipment). If the operator has
//      attached one of HIS OWN records to a sample record, that sample record
//      is NOT deleted at all — it is reported as "kept" instead, with the
//      reason. Removal is allowed to leave sample data behind; it is never
//      allowed to touch the operator's data. See REFERRERS below.
//
// WHY THE ID PREFIX, AND WHERE IT COULD FAIL
//
//   Rejected alternatives:
//     • "created after timestamp X" — a clock is not an identity. A restore,
//       an import, a timezone, or the operator entering a real receipt in the
//       same minute all break it, and it silently over-matches.
//     • "description starts with SAMPLE" — free text. The operator is invited
//       to edit these records (that is the point of practice data), and the
//       moment he does, the mark is gone or, worse, lands on a real row he
//       typed the word "sample" into.
//     • a new `isSample` column — not permitted here, and it would need a
//       schema migration on a live database to add one bit of bookkeeping.
//
//   Known failure modes of the id prefix, stated honestly:
//     a) A row whose id was NOT created by this file could in principle start
//        with `sample-`. In practice it cannot: every id in the schema is
//        `@default(cuid())`, and a cuid is always lowercase alphanumeric
//        starting with `c` — it can never contain a hyphen, so it can never
//        collide with this prefix. The only writer of `sample-` ids in the
//        codebase is this file. If a future feature ever starts assigning
//        hand-written ids, it must not use this prefix.
//     b) Restoring a JSON backup that was taken while sample data existed
//        brings the sample rows back — with their ids intact, so they are
//        still exactly removable. This is the desired behaviour, not a bug.
//     c) A sample row EDITED by the operator is still a sample row, and is
//        still removed. The id does not change when a record is edited, which
//        is precisely why it is the mark. If he wants to keep something he
//        built on top of sample data, he must re-enter it (the removal screen
//        says exactly how many rows are about to go, before they go).
//     d) Removal can be incomplete (case 3 above). It can never be too broad.
//
// A NOTE ON THE VISIBLE "(sample)" LABELS IN THE TEXT BELOW: they are for the
// operator's eyes only, so he can tell practice records from his own at a
// glance on every screen. NO code in this file reads them. Deleting is driven
// by the id and nothing else.
// ═══════════════════════════════════════════════════════════════════════════

import { prisma } from "@/lib/db";
import { taxYearOf } from "@/lib/dates";
import { getBusinessProfile } from "@/lib/business";
import type { Division } from "@/lib/domain";

/** The indelible mark. Every sample row's id begins with this. */
export const SAMPLE_ID_PREFIX = "sample-";

/** Cosmetic only — never used to decide what gets deleted. */
const TAG = "(sample)";

export function isSampleId(id: unknown): id is string {
  return typeof id === "string" && id.startsWith(SAMPLE_ID_PREFIX);
}

/** Builds a sample id. Every create below goes through this — there are no
 *  hand-written id literals, so an unmarked row cannot be generated. */
function sid(...parts: string[]): string {
  return SAMPLE_ID_PREFIX + parts.join("-");
}

// ───────────────────────────── model registry ──────────────────────────────
//
// One entry per record type sample data can create. The list is in DELETE
// ORDER: children before parents, so nothing is ever removed out from under
// something that points at it.

type ModelKey =
  | "filamentUse"
  | "receiptLine"
  | "invoiceLine"
  | "payment"
  | "animalEvent"
  | "maintenanceRecord"
  | "receipt"
  | "printJob"
  | "filamentSpool"
  | "livestockSale"
  | "animal"
  | "invoice"
  | "customer"
  | "expense"
  | "income"
  | "mileageLog"
  | "asset"
  | "vendor"
  | "bankTransaction"
  | "recurringBill"
  | "householdExpense";

/** Models queried only to ask "does a real row point at this?". */
type ReferrerKey = ModelKey | "document";

/** How a row is tied to an account. Every model carries `accountId` except
 *  InvoiceLine, which is scoped through its invoice. */
type AccountScope = { kind: "column" } | { kind: "relation"; through: "invoice" };

type Referrer = {
  model: ReferrerKey;
  /** The column on the referring model that holds the parent's id. */
  field: string;
  /** Extra narrowing (Document rows are typed by `ownerType`). */
  match?: Record<string, unknown>;
  /** Plain-English reason shown to the operator when this blocks a removal. */
  reason: string;
};

type ModelSpec = {
  key: ModelKey;
  /** What the operator calls these, plural. */
  label: string;
  scope: AccountScope;
  /** Rows of the operator's own that would be deleted, blanked or orphaned if
   *  a sample row of this type were removed. Any hit blocks that removal. */
  referrers: Referrer[];
};

const COLUMN: AccountScope = { kind: "column" };

const MODELS: ModelSpec[] = [
  // ── leaves ───────────────────────────────────────────────────────────────
  { key: "filamentUse", label: "Filament used on jobs", scope: COLUMN, referrers: [] },
  { key: "receiptLine", label: "Receipt line items", scope: COLUMN, referrers: [] },
  {
    key: "invoiceLine",
    label: "Invoice line items",
    scope: { kind: "relation", through: "invoice" },
    referrers: [],
  },
  { key: "payment", label: "Payments", scope: COLUMN, referrers: [] },
  { key: "animalEvent", label: "Sheep events", scope: COLUMN, referrers: [] },
  { key: "maintenanceRecord", label: "Maintenance records", scope: COLUMN, referrers: [] },

  // ── things that own leaves ───────────────────────────────────────────────
  {
    key: "receipt",
    label: "Receipts",
    scope: COLUMN,
    referrers: [
      { model: "receiptLine", field: "receiptId", reason: "you added your own line items to it" },
      { model: "filamentSpool", field: "receiptId", reason: "one of your filament spools was bought on it" },
    ],
  },
  {
    key: "printJob",
    label: "Print jobs",
    scope: COLUMN,
    referrers: [
      { model: "filamentUse", field: "printJobId", reason: "you recorded your own filament use on it" },
      {
        model: "document",
        field: "ownerId",
        match: { ownerType: "PRINT_JOB" },
        reason: "you attached your own document to it",
      },
    ],
  },
  {
    key: "filamentSpool",
    label: "Filament spools",
    scope: COLUMN,
    referrers: [
      { model: "filamentUse", field: "spoolId", reason: "one of your own print jobs pulled filament from it" },
    ],
  },
  { key: "livestockSale", label: "Livestock sales", scope: COLUMN, referrers: [] },
  {
    key: "animal",
    label: "Sheep",
    scope: COLUMN,
    referrers: [
      { model: "animalEvent", field: "animalId", reason: "you logged your own event on it" },
      { model: "animalEvent", field: "mateAnimalId", reason: "one of your own breeding records names it" },
      { model: "expense", field: "animalId", reason: "one of your own expenses is charged to it" },
      { model: "livestockSale", field: "animalId", reason: "one of your own sales records it" },
      { model: "animal", field: "sireId", reason: "one of your own sheep has it as a sire" },
      { model: "animal", field: "damId", reason: "one of your own sheep has it as a dam" },
      {
        model: "document",
        field: "ownerId",
        match: { ownerType: "ANIMAL" },
        reason: "you attached your own document to it",
      },
    ],
  },
  {
    key: "invoice",
    label: "Invoices & quotes",
    scope: COLUMN,
    referrers: [
      { model: "invoiceLine", field: "invoiceId", reason: "you added your own line items to it" },
      { model: "payment", field: "invoiceId", reason: "you recorded your own payment against it" },
      { model: "printJob", field: "invoiceId", reason: "one of your own print jobs is billed on it" },
      {
        model: "document",
        field: "ownerId",
        match: { ownerType: "INVOICE" },
        reason: "you attached your own document to it",
      },
    ],
  },
  {
    key: "customer",
    label: "Customers",
    scope: COLUMN,
    referrers: [
      { model: "invoice", field: "customerId", reason: "you invoiced them yourself" },
      { model: "payment", field: "customerId", reason: "you recorded your own payment from them" },
      { model: "printJob", field: "customerId", reason: "one of your own print jobs is for them" },
      { model: "livestockSale", field: "customerId", reason: "one of your own sales is to them" },
      {
        model: "document",
        field: "ownerId",
        match: { ownerType: "CUSTOMER" },
        reason: "you attached your own document to them",
      },
    ],
  },
  {
    key: "expense",
    label: "Expenses",
    scope: COLUMN,
    referrers: [
      { model: "receipt", field: "expenseId", reason: "one of your own receipts is filed against it" },
      { model: "maintenanceRecord", field: "expenseId", reason: "one of your own service records uses it" },
      { model: "animalEvent", field: "expenseId", reason: "one of your own sheep events uses it" },
      { model: "filamentSpool", field: "expenseId", reason: "one of your own spools was bought on it" },
      { model: "bankTransaction", field: "matchedExpenseId", reason: "you matched it to a bank line" },
      {
        model: "document",
        field: "ownerId",
        match: { ownerType: "EXPENSE" },
        reason: "you attached your own document to it",
      },
    ],
  },
  {
    key: "income",
    label: "Income entries",
    scope: COLUMN,
    referrers: [
      { model: "payment", field: "incomeId", reason: "one of your own payments posted it" },
      { model: "livestockSale", field: "incomeId", reason: "one of your own livestock sales posted it" },
      { model: "bankTransaction", field: "matchedIncomeId", reason: "you matched it to a bank line" },
    ],
  },
  { key: "mileageLog", label: "Mileage trips", scope: COLUMN, referrers: [] },
  {
    key: "asset",
    label: "Equipment",
    scope: COLUMN,
    referrers: [
      { model: "maintenanceRecord", field: "assetId", reason: "you logged your own service on it" },
      { model: "expense", field: "assetId", reason: "one of your own expenses is charged to it" },
      { model: "mileageLog", field: "vehicleAssetId", reason: "one of your own trips was driven in it" },
      { model: "printJob", field: "printerAssetId", reason: "one of your own print jobs ran on it" },
      { model: "filamentSpool", field: "printerAssetId", reason: "one of your own spools is loaded on it" },
      {
        model: "document",
        field: "ownerId",
        match: { ownerType: "ASSET" },
        reason: "you attached your own document to it",
      },
    ],
  },
  {
    key: "vendor",
    label: "Vendors",
    scope: COLUMN,
    referrers: [{ model: "expense", field: "vendorId", reason: "one of your own expenses is from them" }],
  },
  { key: "bankTransaction", label: "Bank transactions", scope: COLUMN, referrers: [] },
  { key: "recurringBill", label: "Regular bills", scope: COLUMN, referrers: [] },
  { key: "householdExpense", label: "Household entries", scope: COLUMN, referrers: [] },
];

// ───────────────────────────── prisma plumbing ─────────────────────────────
//
// Prisma's delegates are heavily generic; this file only ever needs three
// operations, uniformly, across twenty-one models. The map below references
// the real `prisma.<model>` properties (so a typo is a compile error), and the
// single cast narrows each delegate to those three calls. The safety of this
// file does NOT rest on the cast: every `where` clause is built by the helpers
// below, never by a caller.

type Row = Record<string, unknown>;

type RowDelegate = {
  count(args: { where: Row }): Promise<number>;
  findMany(args: { where: Row; select: Record<string, boolean> }): Promise<Row[]>;
  deleteMany(args: { where: Row }): Promise<{ count: number }>;
};

const DELEGATES = {
  filamentUse: prisma.filamentUse,
  receiptLine: prisma.receiptLine,
  invoiceLine: prisma.invoiceLine,
  payment: prisma.payment,
  animalEvent: prisma.animalEvent,
  maintenanceRecord: prisma.maintenanceRecord,
  receipt: prisma.receipt,
  printJob: prisma.printJob,
  filamentSpool: prisma.filamentSpool,
  livestockSale: prisma.livestockSale,
  animal: prisma.animal,
  invoice: prisma.invoice,
  customer: prisma.customer,
  expense: prisma.expense,
  income: prisma.income,
  mileageLog: prisma.mileageLog,
  asset: prisma.asset,
  vendor: prisma.vendor,
  bankTransaction: prisma.bankTransaction,
  recurringBill: prisma.recurringBill,
  householdExpense: prisma.householdExpense,
  document: prisma.document,
} satisfies Record<ReferrerKey, unknown>;

function delegate(key: ReferrerKey): RowDelegate {
  return DELEGATES[key] as unknown as RowDelegate;
}

/** InvoiceLine has no accountId column of its own — it is scoped through its
 *  invoice. Everything else carries the column. */
function accountScope(scope: AccountScope, accountId: string): Row {
  return scope.kind === "column" ? { accountId } : { [scope.through]: { accountId } };
}

function scopeOf(key: ReferrerKey, accountId: string): Row {
  const spec = MODELS.find((m) => m.key === key);
  return accountScope(spec ? spec.scope : COLUMN, accountId);
}

/** An account id must be a real, non-empty string before any query runs.
 *  A blank one would widen every `where` clause in this file. */
function assertAccount(accountId: string): void {
  if (typeof accountId !== "string" || accountId.trim() === "") {
    throw new Error("sample-data: an account id is required");
  }
}

// ─────────────────────────────── counting ──────────────────────────────────

export type ModelCount = { key: ModelKey; label: string; count: number };

export type DataOverview = {
  /** Per record type, with zeros included so callers can decide what to show. */
  rows: { key: ModelKey; label: string; sample: number; real: number }[];
  sampleTotal: number;
  realTotal: number;
};

/**
 * How many sample rows exist right now, per model. This is the number the UI
 * shows before and after, so the operator is never guessing.
 */
export async function sampleDataCounts(accountId: string): Promise<ModelCount[]> {
  assertAccount(accountId);
  return Promise.all(
    MODELS.map(async (spec) => ({
      key: spec.key,
      label: spec.label,
      count: await delegate(spec.key).count({
        where: { ...accountScope(spec.scope, accountId), id: { startsWith: SAMPLE_ID_PREFIX } },
      }),
    })),
  );
}

/** Total across a set of per-model counts. */
export function totalOf(counts: { count: number }[]): number {
  return counts.reduce((sum, c) => sum + c.count, 0);
}

/**
 * Sample rows AND real rows, side by side, over the same twenty-one record
 * types. (Settings, passkeys, saved documents and tracker items are not
 * business records — sample data never creates them and never counts them.)
 */
export async function dataOverview(accountId: string): Promise<DataOverview> {
  assertAccount(accountId);
  const rows = await Promise.all(
    MODELS.map(async (spec) => {
      const scope = accountScope(spec.scope, accountId);
      const d = delegate(spec.key);
      const [sample, real] = await Promise.all([
        d.count({ where: { ...scope, id: { startsWith: SAMPLE_ID_PREFIX } } }),
        d.count({ where: { ...scope, NOT: { id: { startsWith: SAMPLE_ID_PREFIX } } } }),
      ]);
      return { key: spec.key, label: spec.label, sample, real };
    }),
  );
  return {
    rows,
    sampleTotal: rows.reduce((s, r) => s + r.sample, 0),
    realTotal: rows.reduce((s, r) => s + r.real, 0),
  };
}

// ─────────────────────────────── removal ───────────────────────────────────

export type KeptGroup = { key: ModelKey; label: string; count: number; reasons: string[] };

export type RemovalReport = {
  /** Per model, what was actually deleted (zeros dropped). */
  removed: ModelCount[];
  removedTotal: number;
  /** Sample rows deliberately left alone because real records hang off them. */
  kept: KeptGroup[];
  keptTotal: number;
  /** The operator's own records, counted after the sweep. Never touched. */
  realTotal: number;
};

/** The sample ids of one model, in id order. */
async function sampleIdsOf(spec: ModelSpec, accountId: string): Promise<string[]> {
  const rows = await delegate(spec.key).findMany({
    where: { ...accountScope(spec.scope, accountId), id: { startsWith: SAMPLE_ID_PREFIX } },
    select: { id: true },
  });
  // Re-checked rather than trusted: only ids that really carry the mark.
  return rows.map((r) => r.id).filter(isSampleId);
}

/**
 * Which of these sample rows have one of the OPERATOR'S OWN rows pointing at
 * them. Those are the rows removal must not touch: deleting them would either
 * cascade into a real record, blank a field on one, or leave one pointing at
 * something that no longer exists.
 */
async function blockedBy(
  spec: ModelSpec,
  accountId: string,
  ids: string[],
): Promise<{ blocked: Set<string>; reasons: string[] }> {
  const blocked = new Set<string>();
  const reasons = new Set<string>();
  if (ids.length === 0 || spec.referrers.length === 0) return { blocked, reasons: [] };

  for (const ref of spec.referrers) {
    const rows = await delegate(ref.model).findMany({
      where: {
        ...scopeOf(ref.model, accountId),
        ...(ref.match ?? {}),
        [ref.field]: { in: ids },
        // "Not a sample row" — i.e. one of the operator's own.
        NOT: { id: { startsWith: SAMPLE_ID_PREFIX } },
      },
      select: { [ref.field]: true },
    });
    for (const row of rows) {
      const parentId = row[ref.field];
      if (typeof parentId === "string") {
        blocked.add(parentId);
        reasons.add(ref.reason);
      }
    }
  }
  return { blocked, reasons: [...reasons] };
}

/**
 * ★ THE ONLY DELETE IN THIS FILE. ★
 *
 * The `where` clause is constructed here and cannot be passed in. It always
 * carries the account scope AND an explicit id list, and every id in that list
 * must pass `isSampleId`. An empty list deletes nothing (Prisma's `in: []`
 * matches no rows) rather than everything.
 */
async function deleteSampleRows(spec: ModelSpec, accountId: string, ids: string[]): Promise<number> {
  assertAccount(accountId);
  const safeIds = ids.filter(isSampleId);
  if (safeIds.length === 0) return 0;
  const result = await delegate(spec.key).deleteMany({
    where: { ...accountScope(spec.scope, accountId), id: { in: safeIds } },
  });
  return result.count;
}

/**
 * Deletes exactly and only the sample rows, children before parents, and
 * reports what went. A sample row that one of the operator's own records is
 * attached to is KEPT and reported — this function will leave sample data
 * behind before it will disturb a real record.
 */
export async function removeSampleData(accountId: string): Promise<RemovalReport> {
  assertAccount(accountId);

  const removed: ModelCount[] = [];
  const kept: KeptGroup[] = [];

  for (const spec of MODELS) {
    const ids = await sampleIdsOf(spec, accountId);
    if (ids.length === 0) continue;

    const { blocked, reasons } = await blockedBy(spec, accountId, ids);
    const removable = ids.filter((id) => !blocked.has(id));

    const count = await deleteSampleRows(spec, accountId, removable);
    if (count > 0) removed.push({ key: spec.key, label: spec.label, count });
    if (blocked.size > 0) {
      kept.push({ key: spec.key, label: spec.label, count: blocked.size, reasons });
    }
  }

  // Counted after the sweep, so the number reported to the operator is the
  // truth as it stands, not a number from before.
  const after = await dataOverview(accountId);

  return {
    removed,
    removedTotal: totalOf(removed),
    kept,
    keptTotal: kept.reduce((s, k) => s + k.count, 0),
    realTotal: after.realTotal,
  };
}

// ─────────────────────────────── generation ────────────────────────────────

export type CreateResult =
  | { ok: true; created: ModelCount[]; total: number }
  | { ok: false; reason: "exists" | "failed"; message: string; existing: number };

/** Local noon, the same convention `parseDateInput` uses, so a calendar day
 *  never shifts across timezones. */
function at(year: number, monthIndex: number, day: number): Date {
  return new Date(year, monthIndex, day, 12, 0, 0);
}

function daysAgo(n: number, from: Date = new Date()): Date {
  return at(from.getFullYear(), from.getMonth(), from.getDate() - n);
}

function daysAhead(n: number, from: Date = new Date()): Date {
  return daysAgo(-n, from);
}

/** n months back, clamped to the 28th so every month has the day. */
function monthsAgo(n: number, from: Date = new Date()): Date {
  return at(from.getFullYear(), from.getMonth() - n, Math.min(from.getDate(), 28));
}

/**
 * Which divisions this business actually uses. The owner's books run
 * FARM / TECH / SHARED; a business signed up later usually has just GENERAL,
 * and sample data must not stamp divisions its screens don't show.
 */
function divisionsFor(divisions: Division[]): { farm: string; tech: string; shared: string } {
  const fallback: string = divisions[0] ?? "GENERAL";
  const pick = (d: Division): string => (divisions.includes(d) ? d : fallback);
  return { farm: pick("FARM"), tech: pick("TECH"), shared: pick("SHARED") };
}

/**
 * Creates one coherent set of practice records across every module.
 *
 * Coherent means the numbers tie together: the payment belongs to its invoice,
 * the lamb's dam is a ewe that exists, the print job's filament came off a
 * spool that exists and its remaining grams already reflect it, the bank line
 * matches the receipt sitting in the Inbox.
 *
 * Everything is written inside ONE transaction, so a failure part-way through
 * leaves nothing behind rather than half a practice world.
 *
 * Refuses when sample data is already present: one practice set at a time
 * keeps the ids stable, keeps "remove all" honest, and keeps the screen
 * simple. Remove first, then add again.
 */
export async function createSampleData(accountId: string): Promise<CreateResult> {
  assertAccount(accountId);

  const existing = totalOf(await sampleDataCounts(accountId));
  if (existing > 0) {
    return {
      ok: false,
      reason: "exists",
      existing,
      message: `There are already ${existing} sample records here. Remove those first, then add a fresh set.`,
    };
  }

  const profile = await getBusinessProfile(accountId);
  const div = divisionsFor(profile.divisions);

  // ── ids ──────────────────────────────────────────────────────────────────
  const id = {
    vendorFeed: sid("vendor", "feed"),
    vendorFilament: sid("vendor", "filament"),
    vendorVet: sid("vendor", "vet"),

    assetTractor: sid("asset", "tractor"),
    assetPrinter: sid("asset", "printer"),
    maintService: sid("maint", "service"),

    expFeed: sid("expense", "feed"),
    expVet: sid("expense", "vet"),
    expFilament: sid("expense", "filament"),
    expHose: sid("expense", "hose"),
    expService: sid("expense", "service"),
    expFuel: sid("expense", "fuel"),
    expPackaging: sid("expense", "packaging"),

    receiptHose: sid("receipt", "hose"),
    receiptLineHose: sid("receiptline", "hose"),
    receiptLineFittings: sid("receiptline", "fittings"),
    receiptInboxFeed: sid("receipt", "inbox", "feed"),
    receiptInboxEmail: sid("receipt", "inbox", "email"),

    custShop: sid("customer", "ridgeline"),
    custBuyer: sid("customer", "wilcox"),

    invoicePartial: sid("invoice", "brackets"),
    invoiceLineBrackets: sid("invoiceline", "brackets"),
    invoiceDraft: sid("invoice", "yarn"),
    invoiceLineYarn: sid("invoiceline", "yarn"),
    quote: sid("invoice", "quote"),
    invoiceLineQuote: sid("invoiceline", "quote"),
    payment: sid("payment", "brackets"),

    incInvoice: sid("income", "brackets"),
    incLamb: sid("income", "lamb"),
    incMarket: sid("income", "market"),
    incDesign: sid("income", "design"),

    tripFeed: sid("mileage", "feed"),
    tripDelivery: sid("mileage", "delivery"),

    ewe1: sid("animal", "ewe1"),
    ewe2: sid("animal", "ewe2"),
    ram: sid("animal", "ram"),
    lambEwe: sid("animal", "lamb1"),
    lambWether: sid("animal", "lamb2"),

    evLambing: sid("event", "lambing"),
    evBirth1: sid("event", "birth1"),
    evBirth2: sid("event", "birth2"),
    evVacc: sid("event", "vaccination"),
    evWeight: sid("event", "weight"),
    evBreeding: sid("event", "breeding"),
    evDeworm: sid("event", "deworming"),

    saleLamb: sid("sale", "lamb"),

    spoolPetg: sid("spool", "petg"),
    spoolPla: sid("spool", "pla"),
    job: sid("job", "brackets"),
    use: sid("use", "brackets"),

    bankIn: sid("bank", "deposit"),
    bankOut: sid("bank", "feedstore"),

    billLease: sid("bill", "lease"),
    billInternet: sid("bill", "internet"),

    houseGroceries: sid("household", "groceries"),
    houseRent: sid("household", "rent"),
    housePay: sid("household", "paycheck"),
  };

  // ── dates ────────────────────────────────────────────────────────────────
  const lambBirth = monthsAgo(7);
  const vaccDate = monthsAgo(4);
  const saleDate = monthsAgo(1);
  const hoseDate = monthsAgo(2);
  const serviceDate = monthsAgo(2);
  const jobStart = daysAgo(44);
  const jobDone = daysAgo(37);
  const invoiceDate = daysAgo(35);
  const paymentDate = daysAgo(21);
  const breedingDate = daysAgo(21);
  const thisMonth = at(new Date().getFullYear(), new Date().getMonth(), 3);

  // Every enum-like string below is a value from src/lib/domain.ts.
  try {
    await prisma.$transaction(
      async (tx) => {
        await tx.vendor.createMany({
          data: [
            { id: id.vendorFeed, accountId, name: `Cedar Creek Feed & Seed ${TAG}` },
            { id: id.vendorFilament, accountId, name: `Northline Filament Co ${TAG}` },
            { id: id.vendorVet, accountId, name: `Oak Hollow Veterinary ${TAG}` },
          ],
        });

        await tx.asset.createMany({
          data: [
            {
              id: id.assetTractor,
              accountId,
              name: `Practice tractor ${TAG}`,
              assetTag: "SAMPLE-EQ-1",
              kind: "Tractor",
              division: div.farm,
              manufacturer: "Kubota",
              model: "L2501",
              year: 2019,
              purchaseDate: monthsAgo(40),
              purchasePriceCents: 2_850_000,
              purchasedFrom: `Cedar Creek Feed & Seed ${TAG}`,
              currentHours: 1240,
              notes: "Practice record. Remove it from Settings → Sample data.",
            },
            {
              id: id.assetPrinter,
              accountId,
              name: `Practice 3D printer ${TAG}`,
              assetTag: "SAMPLE-EQ-2",
              kind: "3D printer",
              division: div.tech,
              manufacturer: "Bambu Lab",
              model: "P1S",
              year: 2025,
              purchaseDate: monthsAgo(14),
              purchasePriceCents: 109_900,
              currentHours: 830,
              notes: "Practice record. Remove it from Settings → Sample data.",
            },
          ],
        });

        // Animals come BEFORE expenses: an expense can be attributed to an
        // animal (Expense.animalId), and the foreign key needs the animal to
        // already exist inside this transaction.
        await tx.animal.createMany({
          data: [
            {
              id: id.ewe1,
              accountId,
              tagNumber: "S101",
              name: `Clover ${TAG}`,
              species: "Sheep",
              breed: "Katahdin",
              sex: "EWE",
              birthDate: monthsAgo(48),
              status: "ACTIVE",
              acquisitionDate: monthsAgo(36),
              acquisitionCostCents: 32_500,
              currentWeightLbs: 155,
              notes: "Practice record.",
            },
            {
              id: id.ewe2,
              accountId,
              tagNumber: "S102",
              name: `Juniper ${TAG}`,
              species: "Sheep",
              breed: "Katahdin",
              sex: "EWE",
              birthDate: monthsAgo(36),
              status: "ACTIVE",
              acquisitionDate: monthsAgo(30),
              acquisitionCostCents: 30_000,
              currentWeightLbs: 148,
              notes: "Practice record.",
            },
            {
              id: id.ram,
              accountId,
              tagNumber: "S201",
              name: `Atlas ${TAG}`,
              species: "Sheep",
              breed: "Katahdin",
              sex: "RAM",
              birthDate: monthsAgo(42),
              status: "ACTIVE",
              acquisitionDate: monthsAgo(24),
              acquisitionCostCents: 55_000,
              currentWeightLbs: 210,
              notes: "Practice record.",
            },
            {
              id: id.lambEwe,
              accountId,
              tagNumber: "S310",
              species: "Sheep",
              breed: "Katahdin",
              sex: "EWE",
              birthDate: lambBirth,
              birthType: "TWIN",
              damId: id.ewe1,
              sireId: id.ram,
              status: "ACTIVE",
              currentWeightLbs: 96,
              notes: "Practice record. Keeper ewe lamb.",
            },
            {
              id: id.lambWether,
              accountId,
              tagNumber: "S311",
              species: "Sheep",
              breed: "Katahdin",
              sex: "WETHER",
              birthDate: lambBirth,
              birthType: "TWIN",
              damId: id.ewe1,
              sireId: id.ram,
              status: "SOLD",
              currentWeightLbs: 112,
              notes: "Practice record. Sold as a market lamb.",
            },
          ],
        });
        await tx.expense.createMany({
          data: [
            {
              id: id.expFeed,
              accountId,
              date: monthsAgo(5),
              taxYear: taxYearOf(monthsAgo(5)),
              vendorId: id.vendorFeed,
              vendorName: `Cedar Creek Feed & Seed ${TAG}`,
              description: `Sheep feed — 12 bags ${TAG}`,
              amountCents: 21_480,
              paymentMethod: "Card",
              division: div.farm,
              accountingCategory: "Feed",
              managementCategory: "Livestock > Feed",
              businessPurpose: "Winter feed for the flock",
              taxStatus: "LIKELY_BUSINESS",
            },
            {
              id: id.expVet,
              accountId,
              date: vaccDate,
              taxYear: taxYearOf(vaccDate),
              vendorId: id.vendorVet,
              vendorName: `Oak Hollow Veterinary ${TAG}`,
              description: `Flock vaccinations — CD&T ${TAG}`,
              amountCents: 18_600,
              paymentMethod: "Card",
              division: div.farm,
              accountingCategory: "Veterinary",
              managementCategory: "Livestock > Medications & vaccines",
              animalId: id.ewe1,
              taxStatus: "LIKELY_BUSINESS",
            },
            {
              id: id.expFilament,
              accountId,
              date: monthsAgo(3),
              taxYear: taxYearOf(monthsAgo(3)),
              vendorId: id.vendorFilament,
              vendorName: `Northline Filament Co ${TAG}`,
              description: `Filament — 2 spools ${TAG}`,
              amountCents: 4_394,
              paymentMethod: "Card",
              division: div.tech,
              accountingCategory: "Supplies",
              managementCategory: "Tech > Filament",
              businessPurpose: "Stock for customer jobs",
              taxStatus: "LIKELY_BUSINESS",
            },
            {
              id: id.expHose,
              accountId,
              date: hoseDate,
              taxYear: taxYearOf(hoseDate),
              vendorId: id.vendorFeed,
              vendorName: `Cedar Creek Feed & Seed ${TAG}`,
              description: `Hydraulic hose + fittings ${TAG}`,
              amountCents: 8_742,
              salesTaxCents: 612,
              paymentMethod: "Card",
              division: div.farm,
              accountingCategory: "Repairs & maintenance",
              managementCategory: `Farm Equipment > Practice tractor ${TAG}`,
              businessPurpose: "Repair the loader hydraulics",
              assetId: id.assetTractor,
              taxStatus: "LIKELY_BUSINESS",
            },
            {
              id: id.expService,
              accountId,
              date: serviceDate,
              taxYear: taxYearOf(serviceDate),
              vendorId: id.vendorFeed,
              vendorName: `Cedar Creek Feed & Seed ${TAG}`,
              description: `Tractor 100-hour service parts ${TAG}`,
              amountCents: 8_950,
              paymentMethod: "Card",
              division: div.farm,
              accountingCategory: "Repairs & maintenance",
              managementCategory: `Farm Equipment > Practice tractor ${TAG}`,
              assetId: id.assetTractor,
              taxStatus: "LIKELY_BUSINESS",
            },
            {
              id: id.expFuel,
              accountId,
              date: daysAgo(42),
              taxYear: taxYearOf(daysAgo(42)),
              vendorName: `Highway 134 Fuel ${TAG}`,
              description: `Diesel — 30 gallons ${TAG}`,
              amountCents: 11_850,
              paymentMethod: "Card",
              division: div.shared,
              accountingCategory: "Vehicle expense",
              // Left as it arrives: the app never decides deductibility.
              taxStatus: "NEEDS_REVIEW",
            },
            {
              id: id.expPackaging,
              accountId,
              date: daysAgo(28),
              taxYear: taxYearOf(daysAgo(28)),
              vendorId: id.vendorFilament,
              vendorName: `Northline Filament Co ${TAG}`,
              description: `Shipping boxes & mailers ${TAG}`,
              amountCents: 4_230,
              paymentMethod: "Card",
              division: div.tech,
              accountingCategory: "Shipping & postage",
              managementCategory: "Tech > Packaging & shipping",
              taxStatus: "LIKELY_BUSINESS",
            },
          ],
        });

        await tx.maintenanceRecord.create({
          data: {
            id: id.maintService,
            accountId,
            assetId: id.assetTractor,
            date: serviceDate,
            hoursAtService: 1200,
            category: "Oil & filters",
            description: `100-hour service — oil, filters, grease ${TAG}`,
            partsCostCents: 8_950,
            vendorName: "Self",
            expenseId: id.expService,
          },
        });

        // Receipts: one filed against its expense (with line items), two
        // waiting in the Inbox — which is the flow worth practising.
        await tx.receipt.createMany({
          data: [
            {
              id: id.receiptHose,
              accountId,
              status: "CATEGORIZED",
              vendorName: `Cedar Creek Feed & Seed ${TAG}`,
              receiptDate: hoseDate,
              totalCents: 8_742,
              salesTaxCents: 612,
              paymentMethod: "Card",
              receiptNumber: "SAMPLE-4471",
              notes: "Practice receipt — no photo attached.",
              expenseId: id.expHose,
            },
            {
              id: id.receiptInboxFeed,
              accountId,
              status: "INBOX",
              vendorName: `Cedar Creek Feed & Seed ${TAG}`,
              receiptDate: daysAgo(12),
              totalCents: 4_327,
              notes: "Practice receipt — try categorizing it from the Inbox.",
            },
            {
              id: id.receiptInboxEmail,
              accountId,
              status: "INBOX",
              source: "EMAIL",
              emailFrom: "orders@example.com",
              emailSubject: `Fwd: Your Northline order ${TAG}`,
              vendorName: `Northline Filament Co ${TAG}`,
              receiptDate: daysAgo(6),
              totalCents: 3_899,
              receiptNumber: "NL-10482",
              notes: "Practice receipt — this is what a forwarded email looks like.",
            },
          ],
        });

        await tx.receiptLine.createMany({
          data: [
            {
              id: id.receiptLineHose,
              accountId,
              receiptId: id.receiptHose,
              sortOrder: 0,
              description: "Hydraulic hose 1/2 in × 48 in",
              quantity: 1,
              amountCents: 7_430,
              accountingCategory: "Repairs & maintenance",
            },
            {
              id: id.receiptLineFittings,
              accountId,
              receiptId: id.receiptHose,
              sortOrder: 1,
              description: "Hose fittings (pair)",
              quantity: 2,
              amountCents: 700,
              accountingCategory: "Repairs & maintenance",
            },
          ],
        });

        await tx.customer.createMany({
          data: [
            {
              id: id.custShop,
              accountId,
              name: `Dana Reyes ${TAG}`,
              company: `Ridgeline Fabrication ${TAG}`,
              phone: "555-0142",
              email: "dana@example.com",
              address: "412 Industrial Way\nSpringfield",
              notes: "Practice customer. Net-14 terms.",
            },
            {
              id: id.custBuyer,
              accountId,
              name: `Martha Wilcox ${TAG}`,
              phone: "555-0188",
              notes: "Practice customer. Buys market lambs each summer.",
            },
          ],
        });

        // A sent invoice, half paid — the state most worth looking at.
        await tx.invoice.createMany({
          data: [
            {
              id: id.invoicePartial,
              accountId,
              number: "SAMPLE-01",
              kind: "INVOICE",
              customerId: id.custShop,
              division: div.tech,
              status: "SENT",
              issueDate: invoiceDate,
              dueDate: daysAgo(21),
              terms: "Due in 14 days",
              taxYear: taxYearOf(invoiceDate),
              subtotalCents: 50_000,
              salesTaxCents: 0,
              totalCents: 50_000,
              notes: `Practice invoice ${TAG}`,
            },
            {
              id: id.invoiceDraft,
              accountId,
              number: "SAMPLE-02",
              kind: "INVOICE",
              customerId: id.custBuyer,
              division: div.farm,
              status: "DRAFT",
              issueDate: daysAgo(4),
              taxYear: taxYearOf(daysAgo(4)),
              subtotalCents: 18_000,
              // 4% of the taxable $180.00 — the same arithmetic computeTax does.
              salesTaxCents: 720,
              totalCents: 18_720,
              taxRatePercent: 4,
              notes: `Practice draft invoice ${TAG}`,
            },
            {
              id: id.quote,
              accountId,
              number: "SAMPLE-Q1",
              kind: "QUOTE",
              customerId: id.custShop,
              division: div.tech,
              status: "SENT",
              issueDate: daysAgo(9),
              dueDate: daysAhead(21),
              terms: "Valid for 30 days",
              taxYear: taxYearOf(daysAgo(9)),
              subtotalCents: 89_500,
              salesTaxCents: 0,
              totalCents: 89_500,
              notes: `Practice quote ${TAG}`,
            },
          ],
        });

        await tx.invoiceLine.createMany({
          data: [
            {
              id: id.invoiceLineBrackets,
              invoiceId: id.invoicePartial,
              sortOrder: 0,
              description: "Conveyor bracket, PETG — printed to drawing",
              quantity: 40,
              unitPriceCents: 1_250,
              totalCents: 50_000,
              taxable: false,
            },
            {
              id: id.invoiceLineYarn,
              invoiceId: id.invoiceDraft,
              sortOrder: 0,
              description: "Wool yarn — 10 skeins",
              quantity: 10,
              unitPriceCents: 1_800,
              totalCents: 18_000,
              taxable: true,
            },
            {
              id: id.invoiceLineQuote,
              invoiceId: id.quote,
              sortOrder: 0,
              description: "Jig fixture set — design + print",
              quantity: 5,
              unitPriceCents: 17_900,
              totalCents: 89_500,
              taxable: false,
            },
          ],
        });

        // Income. Two of these belong to something else (a payment and a
        // livestock sale) and carry the same money, exactly as the app does it.
        await tx.income.createMany({
          data: [
            {
              id: id.incInvoice,
              accountId,
              date: paymentDate,
              taxYear: taxYearOf(paymentDate),
              source: `Ridgeline Fabrication ${TAG}`,
              description: `Invoice SAMPLE-01 — part payment ${TAG}`,
              amountCents: 20_000,
              division: div.tech,
              category: "3D-printed product sales",
              paymentMethod: "Check",
            },
            {
              id: id.incLamb,
              accountId,
              date: saleDate,
              taxYear: taxYearOf(saleDate),
              source: `Martha Wilcox ${TAG}`,
              description: `Market lamb #S311 ${TAG}`,
              amountCents: 34_000,
              division: div.farm,
              category: "Livestock sales",
              paymentMethod: "Check",
            },
            {
              id: id.incMarket,
              accountId,
              date: daysAgo(33),
              taxYear: taxYearOf(daysAgo(33)),
              source: `Farmers market ${TAG}`,
              description: `Wool yarn and lamb shares ${TAG}`,
              amountCents: 14_500,
              division: div.farm,
              category: "Other farm income",
              paymentMethod: "Cash",
            },
            {
              id: id.incDesign,
              accountId,
              date: monthsAgo(4),
              taxYear: taxYearOf(monthsAgo(4)),
              source: `Ridgeline Fabrication ${TAG}`,
              description: `CAD drawing fee ${TAG}`,
              amountCents: 18_000,
              division: div.tech,
              category: "Design / CAD services",
              paymentMethod: "Bank transfer",
            },
          ],
        });

        await tx.payment.create({
          data: {
            id: id.payment,
            accountId,
            invoiceId: id.invoicePartial,
            customerId: id.custShop,
            date: paymentDate,
            amountCents: 20_000,
            method: "Check",
            checkNumber: "1042",
            notes: `Part payment ${TAG}`,
            incomeId: id.incInvoice,
          },
        });

        await tx.mileageLog.createMany({
          data: [
            {
              id: id.tripFeed,
              accountId,
              date: daysAgo(21),
              startLocation: "Farm",
              destination: `Cedar Creek Feed & Seed ${TAG}`,
              purpose: "Feed and mineral pickup",
              startOdometer: 61_240,
              endOdometer: 61_278,
              miles: 38,
              taxYear: taxYearOf(daysAgo(21)),
            },
            {
              id: id.tripDelivery,
              accountId,
              date: daysAgo(10),
              destination: `Ridgeline Fabrication ${TAG}`,
              purpose: "Deliver the bracket order",
              customerName: `Ridgeline Fabrication ${TAG}`,
              miles: 22.4,
              taxYear: taxYearOf(daysAgo(10)),
            },
          ],
        });

        // The flock: two ewes, a ram, and twin lambs out of Clover by Atlas.

        await tx.animalEvent.createMany({
          data: [
            {
              id: id.evLambing,
              accountId,
              animalId: id.ewe1,
              date: lambBirth,
              kind: "LAMBING",
              lambCount: 2,
              description: `Twins, unassisted ${TAG}`,
            },
            {
              id: id.evBirth1,
              accountId,
              animalId: id.lambEwe,
              date: lambBirth,
              kind: "BIRTH",
              weightLbs: 8.4,
              description: `Born ${TAG}`,
            },
            {
              id: id.evBirth2,
              accountId,
              animalId: id.lambWether,
              date: lambBirth,
              kind: "BIRTH",
              weightLbs: 8.9,
              description: `Born ${TAG}`,
            },
            {
              id: id.evVacc,
              accountId,
              animalId: id.ewe1,
              date: vaccDate,
              kind: "VACCINATION",
              productName: "CD&T",
              dosage: "2 mL SQ",
              withdrawalUntil: daysAhead(21, vaccDate),
              costCents: 1_200,
              expenseId: id.expVet,
              description: `Annual booster ${TAG}`,
            },
            {
              id: id.evWeight,
              accountId,
              animalId: id.lambWether,
              date: daysAgo(38),
              kind: "WEIGHT",
              weightLbs: 108,
              description: `Weighed before sale ${TAG}`,
            },
            {
              id: id.evBreeding,
              accountId,
              animalId: id.ewe2,
              date: breedingDate,
              kind: "BREEDING",
              mateAnimalId: id.ram,
              // Sheep gestation, the same 147 days the breeding form suggests.
              dueDate: daysAhead(147, breedingDate),
              description: `Turned in with Atlas ${TAG}`,
            },
            {
              id: id.evDeworm,
              accountId,
              animalId: id.ewe2,
              date: daysAgo(5),
              kind: "DEWORMING",
              productName: "Ivermectin drench",
              dosage: "3 mL oral",
              // Deliberately still in the future, so the withdrawal warning
              // can be seen working on practice data instead of live stock.
              withdrawalUntil: daysAhead(6),
              costCents: 900,
              description: `Routine drench ${TAG}`,
            },
          ],
        });

        await tx.livestockSale.create({
          data: {
            id: id.saleLamb,
            accountId,
            animalId: id.lambWether,
            customerId: id.custBuyer,
            buyerName: `Martha Wilcox ${TAG}`,
            date: saleDate,
            salePriceCents: 34_000,
            weightLbs: 112,
            paymentMethod: "Check",
            incomeId: id.incLamb,
            taxYear: taxYearOf(saleDate),
            notes: `Practice sale ${TAG}`,
          },
        });

        // Filament. The PETG spool's remaining grams already reflect the job
        // below (1000 − 620 used − 48 waste = 332), the way the app keeps it.
        await tx.filamentSpool.createMany({
          data: [
            {
              id: id.spoolPetg,
              accountId,
              manufacturer: `Northline ${TAG}`,
              material: "PETG",
              colorName: "Black",
              spoolTag: "SAMPLE-S1",
              purchaseDate: monthsAgo(3),
              purchasePriceCents: 2_395,
              totalGrams: 1000,
              remainingGrams: 332,
              wasteGrams: 48,
              status: "IN_USE",
              printerAssetId: id.assetPrinter,
              expenseId: id.expFilament,
              notes: "Practice spool.",
            },
            {
              id: id.spoolPla,
              accountId,
              manufacturer: `Northline ${TAG}`,
              material: "PLA",
              colorName: "Slate grey",
              spoolTag: "SAMPLE-S2",
              purchaseDate: monthsAgo(3),
              purchasePriceCents: 1_999,
              totalGrams: 1000,
              remainingGrams: 1000,
              status: "IN_STOCK",
              expenseId: id.expFilament,
              notes: "Practice spool.",
            },
          ],
        });

        await tx.printJob.create({
          data: {
            id: id.job,
            accountId,
            jobNumber: "SAMPLE-J1",
            partName: `Conveyor bracket ${TAG}`,
            partNumber: "RB-2140",
            description: "40 brackets in PETG, printed to the customer's drawing.",
            customerId: id.custShop,
            printerAssetId: id.assetPrinter,
            quantity: 40,
            failedCount: 2,
            printMinutes: 900,
            laborMinutes: 90,
            machineRateCentsPerHour: 50,
            laborRateCentsPerHour: 2_500,
            packagingCostCents: 1_200,
            shippingCostCents: 2_450,
            salePriceCents: 50_000,
            invoiceId: id.invoicePartial,
            status: "SHIPPED",
            startedAt: jobStart,
            completedAt: jobDone,
            notes: `Practice job ${TAG}`,
          },
        });

        await tx.filamentUse.create({
          data: {
            id: id.use,
            accountId,
            printJobId: id.job,
            spoolId: id.spoolPetg,
            grams: 620,
            wasteGrams: 48,
          },
        });

        // Bank lines: one already matched to the payment above, one still
        // unmatched — and it is the feed-store receipt sitting in the Inbox.
        await tx.bankTransaction.createMany({
          data: [
            {
              id: id.bankIn,
              accountId,
              bankName: `Sample Bank ${TAG}`,
              date: paymentDate,
              description: "CHECK DEPOSIT — RIDGELINE FABRICATION",
              amountCents: 20_000,
              // A real fingerprint is a hash of date/description/amount; this
              // one is deliberately un-hash-like so it can never collide.
              fingerprint: sid("fingerprint", "deposit"),
              status: "MATCHED",
              matchedIncomeId: id.incInvoice,
              notes: `Practice bank line ${TAG}`,
            },
            {
              id: id.bankOut,
              accountId,
              bankName: `Sample Bank ${TAG}`,
              date: daysAgo(12),
              description: "CEDAR CREEK FEED #221",
              amountCents: -4_327,
              fingerprint: sid("fingerprint", "feedstore"),
              status: "UNMATCHED",
              notes: "Practice bank line — it matches the receipt in your Inbox.",
            },
          ],
        });

        await tx.recurringBill.createMany({
          data: [
            {
              id: id.billLease,
              accountId,
              description: `Pasture lease ${TAG}`,
              amountCents: 25_000,
              division: div.farm,
              accountingCategory: "Other",
              vendorName: `Hollis land lease ${TAG}`,
              dayOfMonth: 1,
              active: true,
              notes: "Practice bill — nothing is posted to the books without you.",
            },
            {
              id: id.billInternet,
              accountId,
              description: `Shop internet ${TAG}`,
              amountCents: 8_999,
              division: div.tech,
              accountingCategory: "Utilities",
              vendorName: `Springfield Telecom ${TAG}`,
              dayOfMonth: 15,
              active: true,
              notes: "Practice bill.",
            },
          ],
        });

        // Household is the personal side of the app and lives in its own
        // tables, so these can never reach the business books or the Tax
        // Center. (No repeating household items on purpose: those post rows
        // of their own that this file could not mark, and so could not
        // cleanly remove.)
        await tx.householdExpense.createMany({
          data: [
            {
              id: id.houseRent,
              accountId,
              date: thisMonth,
              description: `Rent ${TAG}`,
              amountCents: 120_000,
              kind: "EXPENSE",
              category: "Rent / mortgage",
              paymentMethod: "Bank transfer",
            },
            {
              id: id.houseGroceries,
              accountId,
              date: daysAgo(5),
              description: `Groceries ${TAG}`,
              amountCents: 18_450,
              kind: "EXPENSE",
              category: "Groceries",
              paymentMethod: "Card",
            },
            {
              id: id.housePay,
              accountId,
              date: thisMonth,
              description: `Paycheck ${TAG}`,
              amountCents: 240_000,
              kind: "INCOME",
              category: "Paycheck",
              paymentMethod: "Bank transfer",
            },
          ],
        });
      },
      { timeout: 30_000, maxWait: 15_000 },
    );
  } catch (e) {
    console.error("[sample-data] creation failed:", e);
    // The transaction rolled back, so nothing was left behind. Sweep anyway:
    // it is safe by construction and guarantees a clean slate to retry from.
    await removeSampleData(accountId).catch(() => undefined);
    return {
      ok: false,
      reason: "failed",
      existing: 0,
      message:
        "Sample data could not be added, so nothing was changed. Please try again in a moment.",
    };
  }

  const created = (await sampleDataCounts(accountId)).filter((c) => c.count > 0);
  return { ok: true, created, total: totalOf(created) };
}
