// The sales tax engine's contract. Inputs are plain data (no Prisma), outputs
// are plain JSON (no Date objects) — so a result can be snapshotted as-is and
// any saved return regenerated byte-for-byte from its snapshot.

import type { SalesTaxBasis, SalesTaxTreatment } from "@/lib/domain";

// ————————————————————————————— inputs —————————————————————————————

export type AuthorityIn = {
  id: string;
  name: string;
  level: string; // STATE | COUNTY | CITY | POLICE_JURISDICTION | OTHER
  jurisdictionCode: string;
  taxType: string;
};

export type RateIn = {
  id: string;
  authorityId: string;
  rateClass: string;
  rateTypeCode: string;
  ratePpm: number;
  effectiveFrom: Date;
  effectiveTo: Date | null;
  source: string;
  confirmedAt: Date;
};

export type LocationIn = {
  id: string;
  name: string;
  address: string | null;
  city: string | null;
  county: string | null;
  state: string;
  postalCode: string | null;
  insideCity: boolean;
  policeJurisdiction: string | null;
  authorityIds: string[];
};

export type RuleIn = {
  productType: string;
  treatment: string;
  rateClass: string;
  exemptionReason: string | null;
  requiresEvidence: boolean;
  approvedBy: string;
  approvedAt: Date;
};

export type InvoiceLineIn = {
  id: string;
  sortOrder: number;
  description: string;
  quantity: number;
  unitPriceCents: number;
  totalCents: number;
  taxable: boolean;
  productType: string;
  taxTreatmentOverride: string | null;
  exemptionReason: string | null;
  evidenceDocumentId: string | null;
  originalLineId: string | null;
};

/** Payments in RECORDING order — the order tax is allocated to them in. */
export type PaymentIn = {
  id: string;
  date: Date;
  amountCents: number;
  incomeId: string | null;
  /** The linked Income row's amount (null when there is none). */
  incomeAmountCents: number | null;
};

export type InvoiceIn = {
  id: string;
  number: string;
  kind: string; // INVOICE | QUOTE
  status: string; // DRAFT | SENT | CANCELLED
  division: string;
  issueDate: Date;
  customerId: string;
  customerName: string;
  customerTaxTreatment: string; // DEFAULT | RATE | EXEMPT
  customerExemptReason: string | null;
  customerDocumentIds: string[];
  taxLocationId: string | null;
  subtotalCents: number;
  salesTaxCents: number;
  totalCents: number;
  lines: InvoiceLineIn[];
  payments: PaymentIn[];
};

export type LivestockSaleIn = {
  id: string;
  date: Date;
  salePriceCents: number;
  buyerName: string | null;
  customerId: string | null;
  customerName: string | null;
  animalLabel: string | null;
  animalDocumentIds: string[];
  taxLocationId: string | null;
  taxTreatmentOverride: string | null;
  exemptionReason: string | null;
  incomeId: string | null;
};

export type IncomeIn = {
  id: string;
  date: Date;
  amountCents: number;
  description: string;
  source: string | null;
  category?: string | null;
};

export type EngineInput = {
  period: string; // "2026-09"
  basis: SalesTaxBasis | null;
  basisApprovedBy: string | null;
  authorities: AuthorityIn[];
  rates: RateIn[];
  locations: LocationIn[];
  rules: RuleIn[];
  invoices: InvoiceIn[];
  livestockSales: LivestockSaleIn[];
  incomes: IncomeIn[];
  /** When the result is produced — injected so results are reproducible. */
  generatedAt: Date;
};

// ————————————————————————————— outputs ————————————————————————————

export type LineStatus = "POSTED" | "DISCOUNT" | "RETURN";
export type ReviewStatus = "OK" | "NEEDS_REVIEW";

/** One row per actual invoice/order line reported in the period. */
export type SalesLine = {
  reportPeriod: string;
  lineId: string;
  transactionId: string;
  invoiceNumber: string; // "" for a livestock sale with no invoice
  saleDate: string; // YYYY-MM-DD
  paymentDate: string; // YYYY-MM-DD of final payment, "" if not fully paid
  division: string;
  description: string;
  productType: string;
  customerId: string;
  customerName: string;
  taxLocationId: string;
  locationName: string;
  deliveryAddress: string;
  deliveryCity: string;
  deliveryCounty: string;
  deliveryState: string;
  deliveryPostalCode: string;
  insideCity: boolean | null;
  policeJurisdiction: string;
  /** Revenue. Negative for discounts and returns. */
  pretaxCents: number;
  /** This line's share of the tax actually collected (all authorities). */
  taxCollectedCents: number;
  /** pretax + tax share; summing this column gives the customer totals. */
  totalCents: number;
  status: LineStatus;
  originalLineId: string;
  sourceDocumentId: string;
  treatment: SalesTaxTreatment;
  /** Where the treatment came from, for the audit trail. */
  treatmentSource: "RULE" | "LINE" | "CUSTOMER" | "INVOICE" | "ORIGINAL" | "NONE";
  approvedBy: string;
  exemptionReason: string;
  evidenceDocumentId: string;
  rateClass: string;
  reviewStatus: ReviewStatus;
};

/** One row per sale line PER applicable taxing authority. */
export type TaxComponent = {
  componentId: string; // `${lineId}:${authorityId}` — stable and reproducible
  lineId: string;
  transactionId: string;
  invoiceNumber: string;
  reportPeriod: string;
  authorityId: string;
  authority: string;
  level: string;
  jurisdictionCode: string;
  taxType: string;
  rateType: string; // code as the return shows it
  rateClass: string;
  grossCents: number;
  deductionCents: number;
  taxableCents: number; // gross - deduction
  ratePpm: number | null;
  rateEffectiveDate: string; // the rate row's effectiveFrom, YYYY-MM-DD
  rateSource: string;
  expectedTaxCents: number;
  collectedTaxCents: number;
  differenceCents: number; // collected - expected
  taxTreatment: SalesTaxTreatment;
  exemptionReason: string;
  evidenceDocumentId: string;
  reviewStatus: ReviewStatus;
};

/** One filing row: an authority + rate type, for the period. */
export type SummaryRow = {
  authorityId: string;
  authority: string;
  level: string;
  jurisdictionCode: string;
  taxType: string;
  rateType: string;
  grossCents: number;
  deductionCents: number;
  taxableCents: number;
  /** Distinct rates seen (normally exactly one). */
  ratePpms: number[];
  expectedTaxCents: number;
  collectedTaxCents: number;
  differenceCents: number;
  componentCount: number;
};

export type IssueFix =
  | { kind: "SETUP" }
  | { kind: "INVOICE"; id: string; number?: string }
  | { kind: "LINE"; id: string; invoiceId: string; invoiceNumber?: string }
  | { kind: "LIVESTOCK"; id: string }
  | { kind: "LOCATION"; id: string }
  | { kind: "RATE"; authorityId: string }
  | { kind: "RULE"; productType: string }
  | { kind: "INCOME"; id: string };

export type Issue = {
  code: string;
  severity: "BLOCKER" | "WARNING";
  message: string;
  fix: IssueFix;
};

export type Exclusion = {
  transactionId: string;
  label: string; // "INV-007"
  reason: string;
};

export type EngineTotals = {
  /** Sales counted ONCE (not per authority). Discounts net in; returns don't. */
  grossSalesCents: number;
  /** Returns/refunds issued this period, as a positive amount. */
  returnsCents: number;
  /** Taxable amount on the state return (sum of STATE-level components). */
  stateTaxableCents: number;
  /** Tax summed ACROSS authorities — the only column that adds up that way. */
  expectedTaxCents: number;
  collectedTaxCents: number;
  differenceCents: number;
  /** Tax collected on invoices that could not be allocated (no location). */
  unallocatedCollectedCents: number;
  /** What customers were charged: sales + tax collected. */
  customerTotalCents: number;
  lineCount: number;
  transactionCount: number;
};

export type EngineResult = {
  engineVersion: 1;
  period: string;
  basis: SalesTaxBasis | null;
  basisApprovedBy: string;
  generatedAt: string; // ISO timestamp
  salesLines: SalesLine[];
  components: TaxComponent[];
  summary: SummaryRow[];
  totals: EngineTotals;
  blockers: Issue[];
  warnings: Issue[];
  excluded: Exclusion[];
  readyToFile: boolean;
};
